# Start from the alpine image that is smaller but no fancy tools
FROM alpine:3.13

# User /usr/src/app as our workdir. The following instructions will be executed in the this location
WORKDIR /usr/src/app

# Copy the hello.sh from this location to /usr/src/app creating /usr/src/app/hello.sh
COPY hello.sh .

# Alternatively, if you skipped chmod earlier, you can add execution permissions during the build.
# RUN chmod +x hello.sh

# Execute a command with '/bin/sh -c' prefix
RUN touch additional.txt

# When running docker run the command will be ./hello.sh
CMD ./hello.sh