version: '3.5'

services:

  # https://github.com/docker-hy/material-applications/tree/main/example-frontend
  frontend:
    image: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/
    ports:
      - 5000:5000
    command: ["serve", "-s", "-l", "5000", "build"]

  # https://github.com/docker-hy/material-applications/tree/main/example-backend
  backend:
    image: backend
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
    ports:
      - 8080:8080
    command: ["./server"]