version: '3.5'

services:

  ml-frontend:
    image: ml-frontend
    ports:
      - 3000:3000

  ml-backend:
    image: ml-backend
    ports:
      - 5000:5000
    volumes:
      - ~/ml/ml-model:/src/model
    restart: unless-stopped

  ml-training:
    image: ml-training
    volumes:
      - ~/ml/ml-model:/src/model
      - ~/ml/ml-imgs:/src/imgs
      - ~/ml/ml-data:/data